apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-worker
  namespace: ai-agent-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-worker
  template:
    metadata:
      labels:
        app: rag-worker
    spec:
      containers:
      - name: worker
        image: asif1993/kafka-rag-worker:v1
        env:
        - name: KAFKA_BOOTSTRAP
          value: "kafka.ai-agent-ns.svc.cluster.local:9092"
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: all-secrets-here
              key: GROQ_API_KEY